@startuml
    if(Нужен доступ к элементам по ключу) then (да)
        :Map;
        if(Необходима конкурентная работа) then (да)
            #PaleGreen:TrieMap;
            stop
        else if(Нужен обход в порядке вставки) then (да)
            #PaleGreen:SeqMap;
            stop
        else if(Нужен обход в определенном порядке или range) then (да)
            #PaleGreen:TreeMap;
            stop
        else (нет)
            #PaleGreen:HashMap\n *Map;
            stop
        endif;
    else (нет)
        if(Гарантируем уникальность элементов) then (да)
            :Set;
            if(Нужен обход в порядке вставки) then (да)
                #PaleGreen:LinkedHashSet;
                stop
            else if(Нужен обход в определенном порядке или range) then (да)
                #PaleGreen:SortedSet;
                stop
            else
                #PaleGreen:HashSet\n *Set;
                stop
            endif;
        else (нет)
            :Seq;
            if(FILO) then (да)
                #PaleGreen:Stack;
                stop
            else if(FIFO) then (да)
                #PaleGreen:Queue;
                stop
            else if(доступ по индексу) then (да)
                #PaleGreen:ArrayBuffer;
                stop
            else
                #PaleGreen:ListBuffer;
                stop
            endif;
        endif;
    endif;
@enduml