@startuml
while (Хочется мутабельную коллекцию) is (да)
    #FloralWhite:Не нужно использовать мутабельную коллекцию;
endwhile (нет)
    if(Нужен доступ к элементам по ключу) then (да)
        #PaleGreen:Map;
        stop
    else (нет)
        if(Нужен обход в порядке вставки и не важна уникальность) then (да)
            #PaleGreen:Seq;
            stop
        else (нет)
            #PaleGreen:Set;
            stop
        endif;
    endif;
@enduml